### PR TITLE
Added archiving feature

### PR DESCRIPTION
**Pull request by nainappa**
Added below features.
1. Archiving the reports:
    Just by adding a parameter in testng.xml file, we can archive the reports now. I have already updated readme for this.  
2. Added user name for "Generated By"
     I added username instead of "TESTNG" in the report on the top right corner.

### CODE REVIEW

**Comment by adiralashiva8** [comment]
Thank you @nainappa for your contribution I will look into it

**Comment by nainappa** [comment]
Closing this pull request as there is no response from the owner.

**Comment by adiralashiva8** [comment]
Will try to merge this PR ASAP

**Comment by nainappa** [comment]
Added Total Execution time in "Test Metrics" tab.

**Comment by adiralashiva8** [comment]
I really like this changes
- Archiving reports
- Execution Time

Thanks a lot @nainappa I'm merging this changes and will make few changes in master like 
- Use Current Directory instead of User Name
- Align execution time to right in Test Metrics Tab

**Comment by adiralashiva8** [comment]
TODO: We have used few deprecated methods for this requirement. We need to track those in higher versions

**Pull request merged**
